openapi: 3.0.3
info:
  title: WVMC
  version: 2.0.0
servers:
  - url: http://localhost:8101
    description: localhost
  - url: https://dc.kmsys.ru:53338
    description: Основной сервер
paths:
  /signin:
    post:
      tags:
        - Регистрация и аутентификация
      summary: Вход
      description: Вход по логину паролю
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              email: admin
              password: dev
      responses:
        400:
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  err: Поля email, password  не могут быть пустыми
                  meta: request has empty fields
        500:
          description: Ошибка БД
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  err: Ошибка БД
                  meta: table is not exist
        200:
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              examples:
                success:
                  value:
                    status: ok
                    message:
                      access_token: <token>
                      refresh_token: <token>
                auth_error:
                  value:
                    status: err
                    message:
                      error: Неверный логин или пароль
                      meta: "no migrations rows"
  /refresh:
    post:
      tags:
        - Регистрация и аутентификация
      summary: Обновление пары токенов
      description: Обновление пары токенов
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string
            example:
              application/json
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                refresh_token: <token>
      responses:
        401:
          description: Токен истёк или недействителен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  error: Токен недействителен
                  meta: not valid signature
        400:
          description: Токен отсутствует или имеет неверный тип
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  error: Токен не refresh
                  meta: Token type is not refresh
        500:
          description: Ошибка БД
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  err: Ошибка БД
                  meta: table is not exist
        200:
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: ok
                message:
                  access_token: <token>
                  refresh_token: <token>
  /users:
    get:
      security:
        - bearerAuth: []
      tags:
        - Пользователи
      summary: Просмотр пользователей
      description: Просмотр пользователей приложения
      responses:
        401:
          description: Токен истёк или недействителен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  error: Токен недействителен
                  meta: not valid signature
        500:
          description: Ошибка БД
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  err: Ошибка БД
                  meta: table is not exist
        200:
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: ok
                message:
                  users:
                    - id: "25"
                      name: Сашан
                      email: anaxia@mail.ru
                      company: Сашания
                      role: 1
                    - id: "26"
                      name: Катян
                      email: anaxia@mail.ru
                      company: Катяния
                      role: 0
                    - id: "33"
                      name: Ровшан
                      email: anaxia@mail.ru
                      company: Ровшания
                      role: 1
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - Пользователи
      summary: Создать пользователя
      description:
        Cоздание пользователя приложения.
        
        
        "Поле "role" может принимать следующие значения
        <ul>
        <li>Пользователь **0**</li>
        <li>Администратор **1**</li>
        </ul>
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              name: "Саша"
              company: "Фиксики"
              email: anaxita
              password: qwerty123
              role: 1
      responses:
        401:
          description: Токен истёк или недействителен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  error: Токен недействителен
                  meta: not valid signature
        500:
          description: Ошибка БД
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  err: Ошибка БД
                  meta: table is not exist
        201:
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: ok
                message:
                  id: "74"
    patch:
      security:
        - bearerAuth: [ ]
      tags:
        - Пользователи
      summary: Редактировать пользователя
      description: Редактирование пользователей приложения
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              id: "75"
              name: "Саша"
              company: "Фиксики"
              email: anaxita
              password: qwerty123
              role: 1
      responses:
        401:
          description: Токен истёк или недействителен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  error: Токен недействителен
                  meta: not valid signature
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  error: Пользователь не найден
                  meta: no migrations rows
        500:
          description: Ошибка БД
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  err: Ошибка БД
                  meta: table is not exist
        200:
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: ok
                message: updated
    delete:
      security:
        - bearerAuth: [ ]
      tags:
        - Пользователи
      summary: Удалить пользователя
      description: Удаление пользователя приложения
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              id: "75"
      responses:
        401:
          description: Токен истёк или недействителен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  error: Токен недействителен
                  meta: not valid signature
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  error: Пользователь не найден
                  meta: no migrations rows
        500:
          description: Ошибка БД
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: err
                message:
                  err: Ошибка БД
                  meta: table is not exist
        200:
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                status: ok
                message: Deleted
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Response:
      title: Response
      type: object
      properties:
        status:
          description: Статус ответа
          type: string
          example: ok
        message:
          description: Обект с опциональными данными
          type: object
          example:
            user:
              id: "400"
              name: Alex
    User:
      title: User
      type: object
      properties:
        id:
          description: Уникальный идентификатор
          type: string
          example: "5"
        name:
          description: Имя
          type: string
          example: anaxita
        email:
          description: Логин
          type: string
          example: support@mail.ru
        company:
          description: Компания
          type: string
          example: КМ Системс
        role:
          description: Уровень прав
          type: integer
          example: 0
    Server:
      title: Server
      type: object
      properties:
        id:
          description: Уникальный идентификатор
          type: string
          example: "sdfg-324df-bnn-df-df"
        name:
          description: Имя
          type: string
          example: SRV_SERVER_ONE
        ip4:
          description: IP4 адрес
          type: string
          example: "172.168.12.33"
        hv:
          description: Гипервизор
          type: string
          example: HV07
        user:
          description: Учетная запись
          type: string
          example: Administrator
        password:
          description: Пароль учетной записи
          type: string
          example: qwerty123
        power_status:
          description: Статус работы
          type: integer
          example: 2
        network:
          description: Статус сети
          type: integer
          example: 2